USE GBI_LIQUIDITY

CREATE SCHEMA raw
CREATE SCHEMA work
CREATE SCHEMA final

ALTER TABLE raw.a000_LCR_Account_Mapping 
ALTER COLUMN KeyA VARCHAR(50) NULL;

ALTER TABLE raw.a000_LCR_Account_Mapping 
ALTER COLUMN LCR_Account VARCHAR(50) NULL;

ALTER TABLE raw.a000_LCR_Account_Mapping 
ALTER COLUMN Product_Number VARCHAR(50) NULL;

ALTER TABLE raw.a000_LCR_Account_Mapping 
ALTER COLUMN Sorgu_Final NVARCHAR(250) NULL;

ALTER TABLE raw.a000_LCR_Account_Mapping 
ALTER COLUMN Any_Match NVARCHAR(250) NULL;

Any_Match
