USE GBI_LCR_EXECUTION

ALTER TABLE OUTPUTS.yyy_90_LCR_DATA 
ALTER COLUMN Amount1 Decimal(18,2) NULL;

ALTER TABLE OUTPUTS.yyy_90_LCR_DATA 
ALTER COLUMN Amount4 Decimal(18,2) NULL;

ALTER TABLE OUTPUTS.yyy_90_LCR_DATA 
ALTER COLUMN Amount5 Decimal(18,2) NULL;

ALTER TABLE OUTPUTS.yyy_90_LCR_DATA 
ALTER COLUMN Amount6 Decimal(18,2) NULL;

ALTER TABLE OUTPUTS.yyy_90_LCR_DATA 
ALTER COLUMN Amount7 Decimal(18,2) NULL;

ALTER TABLE OUTPUTS.yyy_90_LCR_DATA 
ALTER COLUMN Amount9 Decimal(18,2) NULL;

ALTER TABLE OUTPUTS.yyy_90_LCR_DATA 
ALTER COLUMN Amount11 Decimal(18,2) NULL;

ALTER TABLE OUTPUTS.yyy_90_LCR_DATA 
ALTER COLUMN Amount14 Decimal(18,2) NULL;

ALTER TABLE OUTPUTS.yyy_90_LCR_DATA 
ALTER COLUMN Amount15 Decimal(18,2) NULL;

ALTER TABLE OUTPUTS.yyy_90_LCR_DATA 
ALTER COLUMN Amount16 Decimal(18,2) NULL;

ALTER TABLE OUTPUTS.yyy_90_LCR_DATA 
ALTER COLUMN Amount17 Decimal(18,2) NULL;

ALTER TABLE OUTPUTS.yyy_90_LCR_DATA 
ALTER COLUMN Amount18 Decimal(18,2) NULL;